<?php

namespace AppBundle\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{

    public function findBySearchKey($key){

        $result = $this->createQueryBuilder('tag')
            ->select(
                'tag.name as tag_name',
                'tag.id as tag_id'
                )
            ->where('tag.name LIKE :key')
            ->setParameter('key', "%$key%")
            ->getQuery()
            ->getArrayResult();

     return $result;
    }

    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function createAlphabeticalQueryBuilder()
    {
        return $this->createQueryBuilder('tag')
            ->orderBy('tag.name', 'ASC');
    }
}
